FROM arm64v8/ubuntu:latest


RUN apt-get update -y && \
    apt-get install -y python3-pip python-dev iputils-ping vim curl

ENV TZ=America/New_York
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update -y && apt-get install -y firefox iproute2 dnsutils nmap

COPY ./geckodriver /usr/local/bin/



RUN pip install --no-cache-dir requests pandas selenium bs4 lxml
RUN pip3 --no-cache-dir uninstall neotime neo4j neobolt 
RUN pip3 --no-cache-dir install neo4j

COPY ./requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt


#CMD [ "bash" ]
COPY . . 
ENTRYPOINT ["gunicorn","-w2","-b 0.0.0.0:5000", "app:app"]
